apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: foodapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foodapp
  template:
    metadata:
      labels:
        app: foodapp
    spec:
      containers:
      - name: frontend
        image: praveen416/frontend
        ports:
        - containerPort: 80
